# config.yaml

# Common parameters shared across all experiments
common:
  project_name: "U-Net_Medical_Segmentation"
  seed: 2981
  # Parameters for the training loop
  training_params:
    num_epochs: 400
    learning_rate: 0.0001
    patience: 400
    batch_size: 8
    
  model_params:
    name: "UGRKAN"
    img_size: 256

# --- Dataset-specific configurations ---
datasets:
  busi:
    dataset_name: "BUSI"
    root_dir: '/kaggle/input/breast-ultrasound-images-dataset/Dataset_BUSI_with_GT'
    num_classes: 1 # Binary segmentation (lesion vs. background)
    # Dataloader and image settings
    dataloader_params:
      batch_size: 8
      img_height: 256
      img_width: 256
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  # Configuration for the CVC-ClinicDB dataset
  cvc_clinicdb:
    dataset_name: "CVC-ClinicDB"
    root_dir: '/kaggle/input/cvcclinicdb/'
    num_classes: 1 # Binary segmentation (lesion vs. background)
    # Dataloader and image settings
    dataloader_params:
      batch_size: 8
      img_height: 256
      img_width: 256
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  cvc_clinicdb:
    dataset_name: "CVC-ClinicDB"
    root_dir: '/kaggle/input/cvcclinicdb/'
    num_classes: 1 # Binary segmentation (lesion vs. background)
    # Dataloader and image settings
    dataloader_params:
      batch_size: 8
      img_height: 256
      img_width: 256
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  glas:
    dataset_name: "GlaS"
    root_dir: '/kaggle/input/glasmiccai2015-gland-segmentation/Warwick_QU_Dataset/'
    num_classes: 1 # Multi-class segmentation (gland vs. background)
    # Dataloader and image settings
    dataloader_params:
      batch_size: 8
      img_height: 512
      img_width: 512
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]